name: Shutdown EC2

on:
  workflow_dispatch:
    inputs:
      instance_id:
        description: 'Instance ID'
        required: true
        type: string

jobs:
  shutdown-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Terminate EC2 instance
        run: |
          aws ec2 terminate-instances --instance-ids ${{ inputs.instance_id }}